<?php

/**
 * @file
 * Primary module hooks for Neo Icon Local Task module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Link;
use Drupal\neo_icon\IconElement;
use Drupal\neo_icon\IconElementInterface;
use Drupal\neo_tooltip\Tooltip;

/**
 * Implements template_preprocess_admin_block().
 */
function neo_icon_admin_preprocess_admin_block(&$variables) {
  $variables['block']['title'] = new IconElement($variables['block']['title'], NULL, NULL, [
    'admin',
  ]);
}

/**
 * Implements template_preprocess_admin_block_content().
 */
function neo_icon_admin_preprocess_admin_block_content(&$variables) {
  foreach ($variables['content'] as $key => &$item) {
    $title = new IconElement($item['title'], NULL, NULL, [
      'admin',
    ]);
    /** @var \Drupal\Core\Url $url */
    $url = $item['url'];
    $attributes = $url->getOption('attributes');
    $attributes['class'][] = 'block';
    $url->setOption('attributes', $attributes);

    $item['link'] = Link::fromTextAndUrl($title, $url);
    if (!empty($item['description'])) {
      $tooltip = new Tooltip($item['description']);
      $tooltip->setPlacementToBottomStart();
      $tooltip->setDelay(200);
      $tooltip->applyToLink($item['link']);
      $variables['#attached'] = array_unique(array_merge($variables['#attached'] ?? [], $tooltip->getAttachments()));
      $item['description'] = '';
    }
  }
}

/**
 * Implements template_preprocess_page_title().
 */
function neo_icon_admin_preprocess_page_title(&$variables) {
  if (!empty($variables['title']) && \Drupal::service('router.admin_context')->isAdminRoute()) {
    if (is_array($variables['title'])) {
      $variables['title'] = \Drupal::service('renderer')->render($variables['title']);
    }
    if (!$variables['title'] instanceof IconElementInterface) {
      $prefix = [];
      $route_match = \Drupal::routeMatch();
      // Entity will be found in the route parameters.
      if (($route = $route_match->getRouteObject()) && ($parameters = $route->getOption('parameters'))) {
        // Determine if the current route represents an entity.
        foreach ($parameters as $name => $options) {
          if (isset($options['type']) && strpos($options['type'], 'entity:') === 0) {
            $entity = $route_match->getParameter($name);
            if ($entity instanceof EntityInterface) {
              $prefix[] = 'entity';
              $prefix[] = 'entity.' . $entity->getEntityTypeId();
            }
          }
        }
      }
      $prefix[] = 'admin';
      $variables['title'] = new IconElement($variables['title'], NULL, NULL, $prefix);
    }
  }
}

/**
 * Implements template_preprocess_links__dropbutton().
 */
function neo_icon_admin_preprocess_links__dropbutton(&$variables) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }
  foreach ($variables['links'] as $key => &$item) {
    if (!empty($item['link']['#title']) && !$item['link']['#title'] instanceof IconElementInterface) {
      $item['link']['#title'] = new IconElement($item['link']['#title'], NULL, NULL, [
        'admin',
      ]);
    }
  }
}

/**
 * Implements template_preprocess_views_view().
 */
function neo_icon_admin_preprocess_views_view(&$variables) {
  foreach ([
    'header',
    'footer',
    'empty',
  ] as $region) {
    if (!empty($variables[$region]) && is_array($variables[$region])) {
      foreach ($variables[$region] as $key => &$item) {
        if (is_array($item) && isset($item['#type'])) {
          switch ($item['#type']) {
            case 'link':
              if (!empty($item['#title']) && !$item['#title'] instanceof IconElementInterface) {
                $item['#title'] = new IconElement($item['#title'], NULL, NULL, [
                  'admin',
                ]);
              }
              break;
          }
        }
      }
    }
  }
}
