neo_icon.entity:
  type: mapping
  label: Entity Icons
  mapping:
    types:
      type: sequence
      label: Types
      sequence:
        type: string

neo_icon.neo_icon_library.*:
  type: config_entity
  label: 'Neo Icon Library'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'The type of icon. Either font or image.'
    file:
      type: string
      label: 'File'
    status:
      type: boolean
      label: 'Status'
    global:
      type: boolean
      label: 'Global'
    unique:
      type: boolean
      label: 'Unique'
    weight:
      type: integer
      label: 'Weight'

neo_icon.entity.third_party:
  type: sequence
  label: Neo Icon
  sequence:
    type: string

field.widget.settings.neo_icon:
  type: mapping
  label: Neo Icon
  mapping:
    include:
      type: sequence
      label: Include
      sequence:
        type: string
    exclude:
      type: sequence
      label: Exclude
      sequence:
        type: string
    icons:
      type: sequence
      label: Icons
      sequence:
        type: string

field.formatter.settings.boolean_icon:
  type: mapping
  mapping:
    format:
      type: string
      label: 'Output format'
    icon_only:
      type: boolean
      label: 'Icon only'
    as_tooltip:
      type: boolean
      label: 'As tooltip'

field.storage_settings.neo_icon:
  type: field.storage_settings.string
  # label: Neo Icon
  # mapping:

node.type.*.third_party.neo_icon:
  type: neo_icon.entity.third_party

taxonomy.vocabulary.*.third_party.neo_icon:
  type: neo_icon.entity.third_party

commerce_order.commerce_order_type.*.third_party.neo_icon:
  type: neo_icon.entity.third_party

profile.type.*.third_party.neo_icon:
  type: neo_icon.entity.third_party

media.type.*.third_party.neo_icon:
  type: neo_icon.entity.third_party
