neo_icon.neo_icon_library.*:
  type: config_entity
  label: 'Neo Icon Library'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'The type of icon. Either font or image.'
    file:
      type: string
      label: File
    status:
      type: boolean
      label: 'Status'
    global:
      type: boolean
      label: 'Global'
    weight:
      type: integer
      label: 'Weight'

neo_icon.entity.third_party:
  type: sequence
  label: Neo Icon
  sequence:
    type: string

node.type.*.third_party.neo_icon:
  type: neo_icon.entity.third_party

taxonomy.vocabulary.*.third_party:
  type: neo_icon.entity.third_party

commerce_order.commerce_order_type.*.third_party:
  type: neo_icon.entity.third_party

profile.type.*.third_party:
  type: neo_icon.entity.third_party

media.type.*.third_party:
  type: neo_icon.entity.third_party
