neo_icon.neo_icon_library.*:
  type: config_entity
  label: 'Neo Icon Library'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'The type of icon. Either font or image.'
    file:
      type: sequence
      sequence:
        type: string
    status:
      type: boolean
      label: 'Status'
    global:
      type: boolean
      label: 'Global'
    weight:
      type: integer
      label: 'Weight'
