<?php

declare(strict_types=1);

namespace Drupal\Tests\neo_icon\Unit;

use Drupal\Component\Serialization\Json;
use Drupal\Tests\UnitTestCase;
use Drupal\neo_icon\IcoMoon\ProjectNormalizer;
use PHPUnit\Framework\Attributes\Group;

/**
 * Specifies what layout normalization reads out of a project file.
 *
 * The parse is the module's only source of glyph names and code points:
 * everything a library can render comes from it. It reads exactly two keys per
 * glyph and drops the rest of a file that runs to tens of megabytes, so a
 * glyph it refuses to read is an icon nobody can put on a page.
 *
 * Parsing is private, so it is observed here through what the pass writes: the
 * synthesized selection.json and the stylesheet carry one entry per surviving
 * glyph, in project order, and the skipped list carries one reason per glyph
 * that did not survive.
 */
#[Group('neo_icon')]
final class GlyphParsingTest extends UnitTestCase {

  use FileSystemMockTrait;
  use IcoMoonPackageBuilderTrait;

  /**
   * It keeps every usable glyph, in the order the project file declared them.
   *
   * Acceptance criterion: *it keeps every usable glyph, in the order the
   * project file declared them.*
   *
   * Order is the package's, never the parser's: IcoMoon writes the glyphs in
   * the order the set was assembled in, and both of the artefacts a library
   * renders from — the stylesheet's content rules and the selection.json's
   * icons — are generated by walking the parse in the order it came back. The
   * fixture's names are deliberately not alphabetical, so a parse that sorted
   * on the way through has nowhere to hide.
   */
  public function testItKeepsEveryUsableGlyphInProjectOrder(): void {
    $package = $this->buildIcoMoonPackage(['woff2'], [
      ['name' => 'zebra', 'code' => 0xE900],
      ['name' => 'alpha', 'code' => 0xE901],
      ['name' => 'mango', 'code' => 0xE902],
    ]);

    $normalizer = $this->normalizePackage($package);

    $this->assertSame(['zebra', 'alpha', 'mango'], $this->selectionNames($package));
    $this->assertSame([0xE900, 0xE901, 0xE902], $this->selectionCodes($package));
    $this->assertSame(['zebra' => 'e900', 'alpha' => 'e901', 'mango' => 'e902'], $this->styleContentRules($package));
    $this->assertSame([], $normalizer->getSkipped(), 'A package of usable glyphs skips none of them.');
  }

  /**
   * It keeps numerically named glyphs as names rather than as indexes.
   *
   * Acceptance criterion: *it keeps a numerically named glyph as a name rather
   * than as an index.*
   *
   * Plenty of icon sets name glyphs "0", "1" and "100", and a name keyed map
   * would turn every one of those into an integer key on the way in — which is
   * why the parse returns a list, as the class says in a comment and nothing
   * until now checked. The damage is not theoretical: the name is written into
   * the selection.json a library is built from and into the class the
   * stylesheet sets the glyph's content on, so a name that came back as an
   * integer is a rule nobody can target. The assertion is strict on purpose,
   * because "0" and 0 compare equal loosely and render differently.
   */
  public function testItKeepsNumericallyNamedGlyphsAsNames(): void {
    $package = $this->buildIcoMoonPackage(['woff2'], [
      ['name' => '0', 'code' => 0xE900],
      ['name' => '1', 'code' => 0xE901],
      ['name' => '100', 'code' => 0xE902],
      ['name' => 'home', 'code' => 0xE903],
    ]);

    $this->normalizePackage($package);

    $this->assertSame(['0', '1', '100', 'home'], $this->selectionNames($package));
    $this->assertSame(['0' => 'e900', '1' => 'e901', '100' => 'e902', 'home' => 'e903'], $this->styleContentRules($package));
  }

  /**
   * It skips glyphs with no name or no integer code point.
   *
   * Acceptance criterion: *it skips a glyph with no name or no integer code
   * point, and reports it as skipped.*
   *
   * A glyph is two scalars, and a glyph missing either of them cannot be
   * rendered — there is no class to write and nothing to set the content from.
   * One malformed glyph does not cost the whole set, though: the rest import
   * and the parse collects a reason per casualty for the import to log. The
   * reasons are asserted by count and by what they identify, never by their
   * wording: the list is a log line, and a later message improvement should not
   * be a test failure. An unnamed glyph's reason has nothing but its position
   * to carry, which is why position is the part every reason is held to.
   */
  public function testItSkipsGlyphsWithNoNameOrNoIntegerCodePoint(): void {
    $package = $this->buildIcoMoonPackage(['woff2'], [
      ['name' => 'alpha', 'code' => 0xE900],
      ['code' => 0xE901],
      ['name' => 'beta', 'code' => '0xE902'],
      ['name' => '', 'code' => 0xE903],
      ['name' => 'gamma', 'code' => 0xE904],
    ]);

    $normalizer = $this->normalizePackage($package);

    $this->assertSame(['alpha', 'gamma'], $this->selectionNames($package));
    $this->assertSame(['alpha' => 'e900', 'gamma' => 'e904'], $this->styleContentRules($package));

    $skipped = $normalizer->getSkipped();

    $this->assertCount(3, $skipped);
    $this->assertSkipReason($skipped[0], 1);
    $this->assertSkipReason($skipped[1], 2, 'beta');
    $this->assertSkipReason($skipped[2], 3);
  }

  /**
   * It skips glyphs repeating a name already taken.
   *
   * Acceptance criterion: *it skips a glyph repeating a name already taken, and
   * reports it as skipped.*
   *
   * A name is what everything downstream addresses a glyph by — the CSS class,
   * the sprite symbol id, the icon the Twig function asks for — so two glyphs
   * cannot share one. The first claim wins and keeps its own code point, which
   * is the part worth pinning: a duplicate that overwrote instead of being
   * dropped would leave the name rendering the wrong glyph rather than an
   * obviously missing one.
   */
  public function testItSkipsGlyphsRepeatingNamesAlreadyTaken(): void {
    $package = $this->buildIcoMoonPackage(['woff2'], [
      ['name' => 'alpha', 'code' => 0xE900],
      ['name' => 'beta', 'code' => 0xE901],
      ['name' => 'alpha', 'code' => 0xE902],
      ['name' => 'gamma', 'code' => 0xE903],
    ]);

    $normalizer = $this->normalizePackage($package);

    $this->assertSame(['alpha', 'beta', 'gamma'], $this->selectionNames($package));
    $this->assertSame([0xE900, 0xE901, 0xE903], $this->selectionCodes($package), 'The first claim on a name keeps its own code point.');
    $this->assertSame(['alpha' => 'e900', 'beta' => 'e901', 'gamma' => 'e903'], $this->styleContentRules($package));

    $skipped = $normalizer->getSkipped();

    $this->assertCount(1, $skipped);
    $this->assertSkipReason($skipped[0], 2, 'alpha');
  }

  /**
   * It refuses a project file carrying no glyphs key at all.
   *
   * Acceptance criterion: *it refuses a project file carrying no glyphs key at
   * all.*
   *
   * A file with no glyphs key is not a thin set, it is not a project file —
   * something else was uploaded, or the export was truncated — so the refusal
   * names the file rather than reporting an empty library. It is also a branch
   * of its own, and one an edit could quietly fold into the "no usable glyphs"
   * refusal beside it without any other test noticing, so the two messages are
   * asserted to differ. Only that they differ: neither wording is pinned. And
   * the refusal lands before anything is moved or deleted, which is what lets a
   * site builder fix the export and upload the same package again.
   */
  public function testItRefusesProjectFileCarryingNoGlyphsKey(): void {
    $keyless = $this->buildIcoMoonPackage(['woff2'], NULL);
    $projectFile = $this->projectFile($keyless);

    $refusal = $this->refuse($keyless)[1];

    $this->assertStringContainsString(basename($projectFile), $refusal, 'The refusal names the file to re-export.');
    $this->assertFileDoesNotExist($keyless . '/selection.json', 'A refused package leaves no library behind.');
    $this->assertFileExists($projectFile, 'The refusal lands before the package is rewritten.');

    $allSkipped = $this->buildIcoMoonPackage(['woff2'], [['code' => 0xE900]]);

    $this->assertNotSame($this->refuse($allSkipped)[1], $refusal, 'An unusable file and an unusable set are refused as the distinct problems they are.');
  }

  /**
   * It refuses a package whose glyphs were all skipped.
   *
   * Acceptance criterion: *it refuses a package whose glyphs were all
   * skipped.*
   *
   * A few unusable glyphs cost a site builder those glyphs; a project file in
   * which every glyph is unusable is a set nobody can render anything from, and
   * importing it would register a library of nothing. The refusal is the other
   * side of the tolerance the skipping buys, and it arrives with the reasons
   * still collected, so the message that says a package cannot be used is
   * accompanied by the per-glyph account of why.
   */
  public function testItRefusesPackageWhoseGlyphsWereAllSkipped(): void {
    $package = $this->buildIcoMoonPackage(['woff2'], [
      ['code' => 0xE900],
      ['name' => 'beta', 'code' => '0xE901'],
      ['name' => '', 'code' => 0xE902],
    ]);
    $projectFile = $this->projectFile($package);

    [$normalizer, $refusal] = $this->refuse($package);

    $this->assertStringContainsString(basename($projectFile), $refusal, 'The refusal names the file to re-export.');
    $this->assertCount(3, $normalizer->getSkipped(), 'Every glyph is still accounted for by a reason.');
    $this->assertFileDoesNotExist($package . '/selection.json', 'A refused package leaves no library behind.');
    $this->assertFileExists($projectFile, 'The refusal lands before the package is rewritten.');
  }

  /**
   * Runs layout normalization over a package the builder wrote.
   *
   * @param string $package
   *   The package directory.
   *
   * @return \Drupal\neo_icon\IcoMoon\ProjectNormalizer
   *   The normalizer, to be asked what it skipped.
   */
  private function normalizePackage(string $package): ProjectNormalizer {
    $normalizer = new ProjectNormalizer($package, 'icon-example', $this->actingFileSystem());
    $normalizer->normalize((string) $normalizer->detect());
    return $normalizer;
  }

  /**
   * Runs layout normalization over a package that cannot become a library.
   *
   * @param string $package
   *   The package directory.
   *
   * @return array
   *   The normalizer, to be asked what it skipped, and the message it refused
   *   the package with.
   */
  private function refuse(string $package): array {
    $normalizer = new ProjectNormalizer($package, 'icon-example', $this->actingFileSystem());
    try {
      $normalizer->normalize((string) $normalizer->detect());
    }
    catch (\Exception $e) {
      return [$normalizer, $e->getMessage()];
    }
    $this->fail('The package was not refused at all.');
  }

  /**
   * The project file of a built package.
   *
   * @param string $package
   *   The package directory.
   *
   * @return string
   *   The project file path.
   */
  private function projectFile(string $package): string {
    $normalizer = new ProjectNormalizer($package, 'icon-example', $this->actingFileSystem());
    return (string) $normalizer->detect();
  }

  /**
   * The glyph names the synthesized selection.json carries, in file order.
   *
   * @param string $package
   *   The package directory.
   *
   * @return array<int, mixed>
   *   One name per surviving glyph.
   */
  private function selectionNames(string $package): array {
    return array_column($this->selectionProperties($package), 'name');
  }

  /**
   * The code points the synthesized selection.json carries, in file order.
   *
   * @param string $package
   *   The package directory.
   *
   * @return array<int, mixed>
   *   One code point per surviving glyph.
   */
  private function selectionCodes(string $package): array {
    return array_column($this->selectionProperties($package), 'code');
  }

  /**
   * The properties of every icon in the synthesized selection.json.
   *
   * @param string $package
   *   The package directory.
   *
   * @return array<int, mixed>
   *   One properties array per surviving glyph, in file order.
   */
  private function selectionProperties(string $package): array {
    $selection = (array) Json::decode((string) file_get_contents($package . '/selection.json'));
    return array_column((array) $selection['icons'], 'properties');
  }

  /**
   * The stylesheet's per-glyph content rules, name to hex code point.
   *
   * @param string $package
   *   The package directory.
   *
   * @return array<string, string>
   *   The hex code point of each rule, keyed by glyph name, in stylesheet
   *   order.
   */
  private function styleContentRules(string $package): array {
    $css = (string) file_get_contents($package . '/style.css');
    preg_match_all('/\.icon-example-([^:\s]+):before \{\s*content: "\\\\([0-9a-f]+)";/', $css, $matches, PREG_SET_ORDER);
    $rules = [];
    foreach ($matches as $match) {
      $rules[$match[1]] = $match[2];
    }
    return $rules;
  }

  /**
   * Asserts that a skipped glyph reason identifies the glyph it is about.
   *
   * @param string $reason
   *   The reason the parse collected.
   * @param int $delta
   *   The glyph's position in the project file.
   * @param string|null $name
   *   The glyph's name, or NULL when it had none to be identified by.
   */
  private function assertSkipReason(string $reason, int $delta, ?string $name = NULL): void {
    $this->assertMatchesRegularExpression('/(?<!\d)' . $delta . '(?!\d)/', $reason, sprintf('The reason identifies the glyph at position %d.', $delta));
    if ($name !== NULL) {
      $this->assertStringContainsString($name, $reason, 'The reason identifies the glyph by name.');
    }
  }

}
